rbac:
  create: true
serviceAccounts:
  alertmanager:
    create: true
    name: null
  kubeStateMetrics:
    create: true
    name: null
  nodeExporter:
    create: true
    name: null
  pushgateway:
    create: true
    name: null
  server:
    create: true
    name: null
alertmanager:
  enabled: true
  name: alertmanager
  image:
    repository: prom/alertmanager
    tag: v0.15.2
    pullPolicy: IfNotPresent
  priorityClassName: ''
  extraArgs: {}
  prefixURL: ''
  baseURL: /
  extraEnv: {}
  configMapOverrideName: ''
  ingress:
    enabled: false
    annotations: {}
    extraLabels: {}
    hosts: []
    tls: []
  tolerations: []
  nodeSelector: {}
  affinity: {}
  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    annotations: {}
    existingClaim: ''
    mountPath: /data
    size: 2Gi
    storageClass: prometheus
    subPath: ''
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  securityContext: {}
  service:
    annotations: {}
    labels: {}
    clusterIP: ''
    externalIPs: []
    loadBalancerIP: ''
    loadBalancerSourceRanges: []
    servicePort: 80
    type: ClusterIP
configmapReload:
  name: configmap-reload
  image:
    repository: jimmidyson/configmap-reload
    tag: v0.2.2
    pullPolicy: IfNotPresent
  extraArgs: {}
  extraConfigmapMounts: []
  resources: {}
initChownData:
  enabled: true
  name: init-chown-data
  image:
    repository: busybox
    tag: latest
    pullPolicy: IfNotPresent
  resources: {}
kubeStateMetrics:
  enabled: true
  name: kube-state-metrics
  image:
    repository: quay.io/coreos/kube-state-metrics
    tag: v1.4.0
    pullPolicy: IfNotPresent
  priorityClassName: ''
  args: {}
  tolerations: []
  nodeSelector: {}
  podAnnotations: {}
  pod:
    labels: {}
  replicaCount: 1
  resources: {}
  securityContext: {}
  service:
    annotations:
      prometheus.io/scrape: 'true'
    labels: {}
    clusterIP: None
    externalIPs: []
    loadBalancerIP: ''
    loadBalancerSourceRanges: []
    servicePort: 80
    type: ClusterIP
nodeExporter:
  enabled: true
  hostNetwork: true
  hostPID: true
  name: node-exporter
  image:
    repository: prom/node-exporter
    tag: v0.16.0
    pullPolicy: IfNotPresent
  podSecurityPolicy:
    enabled: false
  priorityClassName: ''
  updateStrategy:
    type: OnDelete
  extraArgs: {}
  extraHostPathMounts: []
  extraConfigmapMounts: []
  tolerations: []
  nodeSelector: {}
  podAnnotations: {}
  pod:
    labels: {}
  resources: {}
  securityContext: {}
  service:
    annotations:
      prometheus.io/scrape: 'true'
    labels: {}
    clusterIP: None
    externalIPs: []
    hostPort: 9100
    loadBalancerIP: ''
    loadBalancerSourceRanges: []
    servicePort: 9100
    type: ClusterIP
server:
  name: server
  image:
    repository: prom/prometheus
    tag: v2.4.3
    pullPolicy: IfNotPresent
  priorityClassName: ''
  prefixURL: ''
  baseURL: ''
  enableAdminApi: false
  global:
    scrape_interval: 1m
    scrape_timeout: 10s
    evaluation_interval: 1m
  extraArgs: {}
  extraHostPathMounts: []
  extraConfigmapMounts: []
  extraSecretMounts: []
  configMapOverrideName: ''
  ingress:
    enabled: false
    annotations: {}
    extraLabels: {}
    hosts: []
    tls: []
  tolerations: []
  nodeSelector: {}
  affinity: {}
  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    annotations: {}
    existingClaim: ''
    mountPath: /data
    size: 8Gi
    storageClass: prometheus
    subPath: ''
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  securityContext: {}
  service:
    annotations: {}
    labels: {}
    clusterIP: ''
    externalIPs: []
    loadBalancerIP: ''
    loadBalancerSourceRanges: []
    servicePort: 80
    nodePort: 30900
    type: NodePort
  terminationGracePeriodSeconds: 300
  retention: ''
pushgateway:
  enabled: true
  name: pushgateway
  image:
    repository: prom/pushgateway
    tag: v0.5.2
    pullPolicy: IfNotPresent
  priorityClassName: ''
  extraArgs: {}
  ingress:
    enabled: false
    annotations: {}
    hosts: []
    tls: []
  tolerations: []
  nodeSelector: {}
  podAnnotations: {}
  replicaCount: 1
  resources: {}
  securityContext: {}
  service:
    annotations:
      prometheus.io/probe: pushgateway
    labels: {}
    clusterIP: ''
    externalIPs: []
    loadBalancerIP: ''
    loadBalancerSourceRanges: []
    servicePort: 9091
    type: ClusterIP
alertmanagerFiles:
  alertmanager.yml:
    global: {}
    receivers:
      - name: default-receiver
    route:
      group_wait: 10s
      group_interval: 5m
      receiver: default-receiver
      repeat_interval: 3h
serverFiles:
  alerts: {}
  rules: {}
  prometheus.yml:
    rule_files:
      - /etc/config/rules
      - /etc/config/alerts
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - 'localhost:9090'
      - job_name: kubernetes-apiservers
        kubernetes_sd_configs:
          - role: endpoints
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_namespace
              - __meta_kubernetes_service_name
              - __meta_kubernetes_endpoint_port_name
            action: keep
            regex: default;kubernetes;https
      - job_name: kubernetes-nodes
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: 'kubernetes.default.svc:443'
          - source_labels:
              - __meta_kubernetes_node_name
            regex: (.+)
            target_label: __metrics_path__
            replacement: '/api/v1/nodes/${1}/proxy/metrics'
      - job_name: kubernetes-nodes-cadvisor
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: 'kubernetes.default.svc:443'
          - source_labels:
              - __meta_kubernetes_node_name
            regex: (.+)
            target_label: __metrics_path__
            replacement: '/api/v1/nodes/${1}/proxy/metrics/cadvisor'
      - job_name: kubernetes-service-endpoints
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_service_annotation_prometheus_io_scrape
            action: keep
            regex: true
          - source_labels:
              - __meta_kubernetes_service_annotation_prometheus_io_scheme
            action: replace
            target_label: __scheme__
            regex: (https?)
          - source_labels:
              - __meta_kubernetes_service_annotation_prometheus_io_path
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels:
              - __address__
              - __meta_kubernetes_service_annotation_prometheus_io_port
            action: replace
            target_label: __address__
            regex: '([^:]+)(?::\d+)?;(\d+)'
            replacement: '$1:$2'
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - source_labels:
              - __meta_kubernetes_namespace
            action: replace
            target_label: kubernetes_namespace
          - source_labels:
              - __meta_kubernetes_service_name
            action: replace
            target_label: kubernetes_name
      - job_name: prometheus-pushgateway
        honor_labels: true
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_service_annotation_prometheus_io_probe
            action: keep
            regex: pushgateway
      - job_name: kubernetes-services
        metrics_path: /probe
        params:
          module:
            - http_2xx
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_service_annotation_prometheus_io_probe
            action: keep
            regex: true
          - source_labels:
              - __address__
            target_label: __param_target
          - target_label: __address__
            replacement: blackbox
          - source_labels:
              - __param_target
            target_label: instance
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - source_labels:
              - __meta_kubernetes_namespace
            target_label: kubernetes_namespace
          - source_labels:
              - __meta_kubernetes_service_name
            target_label: kubernetes_name
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_scrape
            action: keep
            regex: true
          - source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_path
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels:
              - __address__
              - __meta_kubernetes_pod_annotation_prometheus_io_port
            action: replace
            regex: '([^:]+)(?::\d+)?;(\d+)'
            replacement: '$1:$2'
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels:
              - __meta_kubernetes_namespace
            action: replace
            target_label: kubernetes_namespace
          - source_labels:
              - __meta_kubernetes_pod_name
            action: replace
            target_label: kubernetes_pod_name
extraScrapeConfigs: null
networkPolicy:
  enabled: false
